prompts = [
  "Has played minecraft"
  "Has their own website hosted on the web"
  "First time at Coderdojo!"
  "Has never used Scratch"
  "Is in 5th grade"
  "10 years old"
  "Is in high school"
  "Grew up in Long Island"
  "Lived in five different states"
  "Been at CoderDojo more than three times"
  "Plays an instrument"
  "Wears glasses"
  "Has two or more children"
  "Read a book within the last month"
  "Owns a nintendo ds"
  "Owns a xbox"
  "Owns a playstation"
  "Has a red name tag"
  "Owned a Sega Genesis"
  "Doesn't like spiders"
  "Owns a pet"
  "Likes Hunger Games"
  "Plays basketball"
  "Uses Kik"
  "Under seven years old"
  "Uses Snapchat"
  "Is a lefty"
  "Knows what a floppy disk is"
  "Has a sibling"
  "Is older than 20"
  "Plays video games"
  "Loves ice cream"
  "Is allergic to nuts"
  "Uses Instagram"
  "Has play pokemon card games"
  "Watched Wreck it Ralph"
  "Owned an Atari"
  "Has been to Disney World"
  "Knows how to play chess"
  "Favorite color is magenta"
  "Watches Legend of Korra"
  "Watched a movie within the last week"
  "Watches Avatar Last Air Bender"
  "Has programmed Android"
  "Has been to Europe"
  "Owns a car"
  "Took more than 2 hours to get here"
  "Played Neopets"
  "Plays the Sims"
  "Attended a concert"
  "Has a last name with more than 10 characters"
  "Plays a violin"
  "Lived on the West Coast for more than a year"
  "Is a designer"
  "Is a software developer"
  "Knows how to code in Python"
  "Knows how to code iOS"
  "Has an app on the Apple App Store"
  "Owns an iPhone"
  "Owns an Android"
  "Has a Tumblr"
  "Owned a Super Nintendo"
  "Has not played Angry Birds"
  "Has over 30 points in Flappy Birds"
  "Plays Clash of Clans"
  "Enjoys Black Coffee"
  "Enjoys Tea"
  "Part of Technovation"
  "Is a part of Nano Hackers"
  "Favorite season is Summer"
  "Favorite season is Winter"
  "Has been to ThoughtWorks"
  "First time mentoring"
  "Told a friend about Coderdojo"
  "Loves Pixar Movies"
  "Is still in school"
]

window.onload = ->
  document.querySelectorAll('tr:nth-child(4) td:nth-child(4)')[0].className = 'blank'
  shuffle(prompts)
  for td in document.querySelectorAll('td:not(.blank)')
    td.innerHTML = prompts.pop()


# Functions
swap = (ary, a, b) -> temp = ary[b]; ary[b] = ary[a]; ary[a] = temp; ary
shuffle = (ary) ->
  for i in [1..100]
    length = ary.length
    swap(ary, i % length, parseInt(Math.random() * length))
